name: compact_piano
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0  # для воспроизведения звуков клавиш
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  flutter_cache_manager: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffmpeg_kit_flutter: 6.0.3  # для записи и экспорта аудио

flutter:
  uses-material-design: true
  assets:
    - assets/notes/
